name: Build Flet App for macOS and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          elif [ -f "pyproject.toml" ]; then
            pip install -e .
          fi

      - name: Set Python IO Encoding to UTF-8 (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "Setting Python IO Encoding to UTF-8"
          set PYTHONIOENCODING=utf-8

      - name: Install PyInstaller
        run: |
          python -m pip install pyinstaller

      - name: Build the Flet App with PyInstaller (macOS or Windows)
        run: |
          pyinstaller --onefile main.py

      # Upload the artifact (the built executable in the dist folder)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: flet-app-build
          path: dist/*  # This assumes PyInstaller's output is in the 'dist/' folder

  download_artifacts:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: flet-app-build
          path: ./downloaded-artifacts  # Location to save the downloaded files
