name: Build Flet App for macOS and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (macOS/Windows)
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") {
              pip install -r requirements.txt
          } elseif (Test-Path "pyproject.toml") {
              pip install -e .
          }
        shell: pwsh  # Use PowerShell (pwsh) instead of bash for Windows

      - name: Install Flet CLI
        run: pip install flet

      - name: Build for macOS
        if: runner.os == 'macOS'
        run: flet build macos --output ./build_output

      - name: Build for Windows
        if: runner.os == 'Windows'
        run: flet build windows --output ./build_output

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flet-app-build
          path: ./build_output/*
