name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Define the platforms you want to target

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python (for pyinstaller and pyinstaller-versionfile)
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify the desired Python version

    - name: Install dependencies (Linux/macOS/Windows)
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyinstaller-versionfile

    - name: Run the build shell script
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          # Windows-specific setup, if any, can go here
          echo "Running on Windows"
        fi
        if [ "${{ runner.os }}" == "macOS" ]; then
          # macOS-specific setup, if any, can go here
          echo "Running on macOS"
        fi

        # Execute the shell script to build the app
        ./deploy/python3 exec_deploy.py

    - name: Upload Windows artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: windows-app
        path: deploy/output/windows/dist/Bianche.exe  # Adjust this to your actual Windows app location

    - name: Upload macOS artifact
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v3
      with:
        name: macos-app
        path: deploy/output/macOS/dist/Bianche.app  # Adjust this to your actual macOS app location
