name: Build and Deploy

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]  # Only macOS and Windows
        python: [3.11]  # Use Python 3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build app
        run: |
          flet pack main.py --name counter --icon icon.png --product-name counter --product-version "1.2.3" --copyright "Copyright (c) 2022 YourCompany Inc."

      - name: Create package
        run: |
          if [[ $RUNNER_OS == 'macOS' ]]; then
            tar -czvf counter-macos.tar.gz -C dist counter.app
            echo "counter-macos.tar.gz" >> $GITHUB_ENV
          elif [[ $RUNNER_OS == 'Windows' ]]; then
            7z a counter-windows.zip %CD%\dist\*.exe
            echo "counter-windows.zip" >> $GITHUB_ENV
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: counter-artifact
          path: ${{ env.counter-artifact }}

  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest  # Deploy on ubuntu-latest
    steps:
      - name: Deploy to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.counter-artifact }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
