name: All Builds (Windows, macOS, Android - APK & AAB)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch: # Allows you to manually trigger the workflow

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11
  FLUTTER_VERSION: 3.22.2

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Build for Windows
        run: |
          flutter config --no-analytics
          flet build windows --verbose --no-rich-output --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifact
          path: build/windows
          if-no-files-found: warn

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Build for macOS
        run: |
          flutter config --no-analytics
          flet build macos --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-artifact
          path: build/macos
          if-no-files-found: warn
