name: Build Flet App for macOS and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          elif [ -f "pyproject.toml" ]; then
            pip install -e .
          fi

      - name: Install Flet CLI
        run: pip install flet

      - name: Build for macOS
        if: runner.os == 'macOS'
        run: flet build macos --output ./build_output

      - name: Build for Windows
        if: runner.os == 'Windows'
        run: flet build windows --output ./build_output

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flet-app-build
          path: ./build_output/*
