name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]  # Define the platforms you want to target

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python (for pyinstaller and pyinstaller-versionfile)
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify the desired Python version

    - name: Install dependencies (macOS/Windows)
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyinstaller-versionfile

    - name: Run the build shell script
      run: |
        # Check the OS and run platform-specific code
        if [ "${{ runner.os }}" == "Windows" ]; then
          # PowerShell on Windows, use appropriate syntax
          echo "Running on Windows"
          # Add any Windows-specific setup or installation if needed
        elif [ "${{ runner.os }}" == "macOS" ]; then
          # macOS-specific setup
          echo "Running on macOS"
        fi

        # Execute the Python script to build the app
        python3 deploy/exec_deploy.py

    - name: Upload Windows artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: windows-app
        path: deploy/output/windows/dist/*  # Adjust this to your actual Windows app location

    - name: Upload macOS artifact
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v3
      with:
        name: macos-app
        path: deploy/output/macOS/dist/*  # Adjust this to your actual macOS app location
