name: Build Flet App for macOS and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      # Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies for both macOS and Windows
      - name: Install dependencies (macOS/Windows)
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          elif [ -f "pyproject.toml" ]; then
            pip install -e .
          fi
        shell: bash # Use bash for macOS/Linux, default PowerShell on Windows

      # Install Flutter SDK on macOS and Windows (if not already available)
      - name: Install Flutter SDK (macOS/Windows)
        run: |
          if [ $RUNNER_OS == 'macOS' ]; then
            # Install Flutter for macOS
            brew install --cask flutter
            flutter doctor
          fi
          if [ $RUNNER_OS == 'Windows' ]; then
            # Install Flutter for Windows
            choco install flutter
            flutter doctor
          fi
        shell: bash

      # Install Flet CLI
      - name: Install Flet CLI
        run: pip install flet

      # Build for macOS
      - name: Build for macOS
        if: runner.os == 'macOS'
        run: flet build macos --output ./build_output

      # Build for Windows
      - name: Build for Windows
        if: runner.os == 'Windows'
        run: flet build windows --output ./build_output

      # Upload the build artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flet-app-build
          path: ./build_output/*
