name: Build and Package Flet App for Apple Silicon

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build the app for macOS (Apple Silicon)
      - name: Build for macOS (Apple Silicon)
        if: matrix.os == 'macos-latest'
        run: python3 deploy/exec_deploy.py

      # Step 4: Build the app for Windows
      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: python3 deploy/exec_deploy.py

      # Step 5: Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Flet-App-${{ matrix.os }}
          path: deploy/output/*/dist/*
