name: All Builds (Linux, macOS, Windows, Android, IPA, APK, AAB)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch: # Allows you to manually trigger the workflow

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11
  FLUTTER_VERSION: 3.22.2

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Build for Linux
        run: |
          flutter config --no-analytics
          flet build linux --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifact
          path: build/linux
          if-no-files-found: warn

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Build for macOS
        run: |
          flutter config --no-analytics
          flet build macos --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-artifact
          path: build/macos
          if-no-files-found: warn

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Build for Windows
        run: |
          flutter config --no-analytics
          flet build windows --verbose --no-rich-output --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifact
          path: build/windows
          if-no-files-found: warn

  build-aab:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Build AAB
        run: |
          flutter config --no-analytics
          flet build aab --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aab-build-artifact
          path: build/aab
          if-no-files-found: warn

  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build APK
        run: |
          flutter config --no-analytics
          flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-build-artifact
          path: build/apk
          if-no-files-found: warn

  build-ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Build IPA
        run: |
          flutter config --no-analytics
          flet build ipa --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipa-build-artifact
          path: build/ipa
          if-no-files-found: warn
